var worldMap=[
    [
        'P   ',
        ' B  ',
        '  B ',
        '   O',
    ],
    [
        'P   ',
        ' B  ',
        '  B ',
        '   B',
        '   B',
        '   B',
        '   O',
    ],
    [
        'X   ',
        'BB  ',
        'BBB ',
        'B XB',
        'O XB',
        'X BB',
        '  PB',
    ],
    [
        'TXXXXXXT',
        'BXXXXXXB',
        'BXXXXXXB',
        'BXXXXXXB',
        'BXXXXXXB',
        'OXXXXXXP',
    ],
    [
        '                      O',
        '   T         T        B',
        '  XB         BB       B',
        '  BB         BBB      B',
        '  BB          BBB     B',
        '  B            BB     B',
        '  B             T     T',
        '  T     T              ',
        '        B              ',
        '        B              ',
        'T    T  B              ',
        'B     B B              ',
        'B      BB              ',
        'B       B              ',
        'P                      ',
    ],
    [
        'B  ',
        'BB ',
        'BSB',
        'BSB',
        'OSB',
        ' SB',
        '  P',
    ],
    [
        '         T            T',
        '         BB            ',
        '         BBB           ',
        '         BBBB          ',
        'TS       TBPBB        O',
        'ST        BBBT        B',
        '           BBB        B',
        '            BB        B',
        '             T        T',
    ],
    [
        'TXXXXXXXT',
        'XOSXXBBBB',
        'XSSXXBBBB',
        'XBSBBBXBX',
        'XBBBBBBBX',
        'XPXBXXXBX',
    ],
    [
        '       B    ',
        ' B SS       ',
        ' BBPO       ',
        ' B BST     T',
        '  B        B',
        'B T  T BXBXB',
        '      BBBBBB',
        '       BXBXB',
    ],
    [
        'O   ',
        'Bx  ',
        'Bxx ',
        'BxxB',
        'BxxB',
        ' xxB',
        '  xB',
        '   P',
    ],
    [
        'P     ',
        ' x    ',
        '  B   ',
        '   x  ',
        '    B ',
        '     x',
        '     B',
        '     x',
        '     B',
        '     x',
        '     B',
        '     O',
    ],
    [
        'O    ',
        'BB   ',
        'XBB  ',
        'XXBB ',
        'XXxBB',
        'XXXxB',
        'BXxBX',
        'BBxxX',
        ' BBXX',
        '  PBX',
        '   BB',
        '    B',
    ],
    [
        'P    ',
        ' x   ',
        '  x  ',
        '   x ',
        '    O',        
    ],
    [
        'P   ',
        ' x  ',
        '  x ',
        '   B',
        '   x',
        '   x',
        '   O',
    ],
    [
        'P    ',
        ' x   ',
        'O x  ',
        'B  x ',
        'B   B',
        ' x  x',
        '  x x',
        '   xx',
        '    B',
    ],
    [],
];